version: "3.8"

services:
  application:
    build:
      dockerfile: application.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=colaboratory

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=colaboratory